### ISSUE TITLE
import-anchors script applies wrong values?

### ISSUE THREAD

**Issue by benwiggy** [knutnergaard/smufolib#1]
The import-anchors script imports the anchors to the wrong position. I'm guessing that the co-ordinates from the JSON file are not multiplied by 250 (converting between 'spaces' and "font units").

They all go to 0,0 or 1,0. 

<img width="331" alt="Screenshot" src="https://github.com/user-attachments/assets/73e18331-708e-4ab0-9e7f-3564777d3117">

**Comment by benwiggy** [comment]
I added a rather crude:
```
                position[0]*=250
                position[1]*=250
```

at line 119, and it works perfectly.

<img width="635" alt="Screenshot" src="https://github.com/user-attachments/assets/34316ad0-aa59-4264-8006-6f06590a1527">

**Comment by knutnergaard** [comment]
@benwiggy As your own efforts suggest, this is a bug that will be corrected in the next update.

Thank you!
